version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      time: "03:00"
      timezone: "Europe/Warsaw"
    open-pull-requests-limit: 10
    groups:
      all-dependencies:
        update-types:
          - "major"
          - "minor"
          - "patch"
    commit-message:
      prefix: "deps"
      include: "scope"
